### ISSUE TITLE
C Program to convert to binary and increment/decrement the number

### ISSUE THREAD

**Issue by Devipriya96** [hari-eur/Somnath-babu---Devipriya#2]
Write a C program to check if a given number contains 2 or more consecutive ones in its binary representation. If it does, then increment the number by 1. Otherwise, decrement the number by 1.

**Comment by somnathnr1165** [comment]
[Consective ones.txt](https://github.com/hari-eur/Somnath-babu---Devipriya/files/10823151/Consective.ones.txt)
